export { TestCorePage } from './TestCorePage'
export { TestThemeSharedPage } from './TestThemeSharedPage'
export { TestThemeBasicPage } from './TestThemeBasicPage'
export { TestAccountPage } from './TestAccountPage'
export { TestPermissionManagementPage } from './TestPermissionManagementPage'
export { TestTenantManagementPage } from './TestTenantManagementPage'
export { TestIdentityPage } from './TestIdentityPage'
